### ISSUE TITLE
Windows Installation Error

### ISSUE THREAD

**Issue by agnim25** [jvkersch/pyconcorde#16]
I get the following error after running "pip install -e .":
f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1

**Comment by jvkersch** [comment]
@agnim25 Unfortunately Windows is not supported (unless you can get Concorde to build reliably on a recent version on Windows. I couldn't invest much time in this, since I don't have a Windows development environment).

**Comment by jvkersch** [comment]
I'll close this now but feel free to reopen if there is new information or if you want to discuss further.
