### ISSUE TITLE
TSPSolver.solve's time_bound arg has no effect

### ISSUE THREAD

**Issue by yairbeer** [jvkersch/pyconcorde#17]
Hi,
I'm trying to use this for Kaggle's competition (197k cities). Is it possible that time_bound above a certain value has no effect? It works up to about 60.0. Above that, the solver never stops and I can't get the results from the solver.

Thanks a lot,
Yair

**Comment by alsauve** [comment]
I have taken a look at the source code and there is indeed some code for checking the time bound but the algorithm is complex and there may be a loop somewhere taking a lot of time without checking it

**Comment by jvkersch** [comment]
I've noticed this too, and as @alsauve reports this is an intricacy with concorde itself. I will close this issue as wontfix since I am not sure how to address it, but please let me know if you have any ideas.
