### ISSUE TITLE
Concorde will not work if multiple versions of python are installed.

### ISSUE THREAD

**Issue by kaasknak** [jvkersch/pyconcorde#19]
On ubuntu server 16.04.5 when following the exact manual as it is written in the README when trying to execute an example script using python3 it will claim that concorde is a missing module.

**Comment by jvkersch** [comment]
@kaasknak Thanks for the report. Can you copy-paste the exact error message that is produced?

**Comment by jvkersch** [comment]
Closing as inactive, but feel free to reopen if more information arises.
