### ISSUE TITLE
if i want define the distance between cities rather than EUC_2D，what i need do in the code

### ISSUE THREAD

**Issue by TryingZ** [jvkersch/pyconcorde#21]
when i use it to solve the TSP，i need consider more factors to calculate the “distance”，between cities，i do not find the way to define my “distance”，do you know how to solve this？thanks

**Comment by jvkersch** [comment]
@TryingZ Sorry for the late follow-up. You can supply a `norm` argument to solver, where `norm` is any allowed norm from https://github.com/jvkersch/pyconcorde/blob/master/concorde/util.py#L3-L14. If that doesn't fit your need, the new API that I'm planning for pyconcorde 0.2.0 will allow you to pre-compute a matrix of distances and supply that. See https://github.com/jvkersch/pyconcorde/issues/28#issuecomment-770354999 for more details.

I will close this issue for now, but please let me know if you have any further questions.
