### ISSUE TITLE
I'm having trouble with Cython

### ISSUE THREAD

**Issue by pcezanne** [jvkersch/pyconcorde#26]
I was able to install Cython, with "brew install python" but when I do the 'pip install -e .' command I get some error centering on Cython.

        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'

**Comment by iliailmer** [comment]
@pcezanne you may need to run `pip install -U cython` to install cython, if you have not already

**Comment by jvkersch** [comment]
Just as a heads-up, the next version (0.2.0) will run concorde in a subprocess, thus removing the need for Cython. You can get a sneak preview of this API in https://github.com/jvkersch/pyconcorde/issues/28#issuecomment-770354999
