### ISSUE TITLE
Running pyconcorde simultaneously

### ISSUE THREAD

**Issue by legohyl** [jvkersch/pyconcorde#31]
Hi there, it seems that I'm unable to run separate pieces of code that uses `pyconcorde`. It appears that `pyconcorde` tries to save the temporary file into a common name, hence, parallel calls will clash on this. Here's the error message I see
```
Nname.pul already exists, renaming to Nname.pul~
Nname.pul~: No such file or directory
Couldn't rename Nname.pul to Nname.pul~
CCutil_sopen failed
CCtsp_write_cutpool failed
failure in cutting_loop
Ctsp_cutting_loop failed
tsp_solve_lp failed
```

**Comment by legohyl** [comment]
Found out that this is because of the same file name being used. Hence, `pyconcorde` can be called in parallel. Submitted a pull request to generate a unique file name.

https://github.com/jvkersch/pyconcorde/pull/32

**Comment by jvkersch** [comment]
Thank you for diagnosing and fixing this issue!
