### ISSUE TITLE
LP solver link error

### ISSUE THREAD

**Issue by iliailmer** [jvkersch/pyconcorde#38]
I get the following message when running the README example:
```
need to link an lp solver to use this function
CClp_create_info failed
need to link an lp solver to use this function
CCtsp_read_probfile or first_lp failed
need to link an lp solver to use this function
CCtsp_init_lp failed
```
I run the program on an M1 Mac, and the latest compatible QSopt is downloaded to the `pyconcorde/data/ directory. The `concorde.h` and `concorde.a` I built manually and also put into the `pyconcorde/data/` directory. What could cause the linking issue here? Thanks!

**Comment by iliailmer** [comment]
@jvkersch Thank you for your response! There is a build for M1 macos 11: https://www.math.uwaterloo.ca/~bico/qsopt/downloads/downloads.htm

**Comment by jvkersch** [comment]
Oh, nice find! What you could do is clone the repo, and change the paths in https://github.com/jvkersch/pyconcorde/blob/cc1f5e0462e7abdae829f65e12610f49c0c97195/setup.py#L38-L41 to point to the M1 build, and then build from scratch.

**Comment by iliailmer** [comment]
Thanks, will do!
