### ISSUE TITLE
How to solve this debug on Ubuntu 18.04? I'can't find any relevant information about this error.. Can anyone help me to solove the problem?

### ISSUE THREAD

**Issue by Williamlittlewhite** [jvkersch/pyconcorde#40]
ERROR: Command errored out with exit status 1:
     command: /home/williamwhites/anaconda3/envs/TSP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/williamwhites/pyconcorde/setup.py'"'"'; __file__='"'"'/home/williamwhites/pyconcorde/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/williamwhites/pyconcorde/
    Complete output (335 lines):
    running develop
    running egg_info
    writing pyconcorde.egg-info/PKG-INFO
    writing dependency_links to pyconcorde.egg-info/dependency_links.txt
    writing requirements to pyconcorde.egg-info/requires.txt
    writing top-level names to pyconcorde.egg-info/top_level.txt
    reading manifest file 'pyconcorde.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'COPYING'
    writing manifest file 'pyconcorde.egg-info/SOURCES.txt'
    running build_ext
    ./concorde/
    ./concorde/Makefile.in
    ./concorde/configure.in
    ./concorde/configure
    ./concorde/aclocal.m4
    ./concorde/config.guess
    ./concorde/config.sub
    ./concorde/install-sh
    ./concorde/BIGGUY/
    ./concorde/BIGGUY/bg_test.c
    ./concorde/BIGGUY/bigguy.c
    ./concorde/BIGGUY/bigguy.tst
    ./concorde/BIGGUY/Makefile.in
    ./concorde/COMBS/
    ./concorde/COMBS/block.c
    ./concorde/COMBS/co_main.c
    ./concorde/COMBS/dngreedy.c
    ./concorde/COMBS/Makefile.in
    ./concorde/CUT/
    ./concorde/CUT/connect.c
    ./concorde/CUT/cut_st.c
    ./concorde/CUT/gomoryhu.c
    ./concorde/CUT/lin_all.c
    ./concorde/CUT/mc_main.c
    ./concorde/CUT/mincut.c
    ./concorde/CUT/segments.c
    ./concorde/CUT/shrink.c
    ./concorde/CUT/Makefile.in
    ./concorde/EDGEGEN/
    ./concorde/EDGEGEN/delaunay.c
    ./concorde/EDGEGEN/edgegen.c
    ./concorde/EDGEGEN/eg_main.c
    ./concorde/EDGEGEN/mlinkern.c
    ./concorde/EDGEGEN/xnear.c
    ./concorde/EDGEGEN/Makefile.in
    ./concorde/FMATCH/
    ./concorde/FMATCH/fmatch.c
    ./concorde/FMATCH/fm_main.c
    ./concorde/FMATCH/Makefile.in
    ./concorde/HELDKARP/
    ./concorde/HELDKARP/heldkarp.c
    ./concorde/HELDKARP/hk_main.c
    ./concorde/HELDKARP/Makefile.in
    ./concorde/INCLUDE/
    ./concorde/INCLUDE/bigguy.h
    ./concorde/INCLUDE/combs.h
    ./concorde/INCLUDE/consec1.h
    ./concorde/INCLUDE/cut.h
    ./concorde/INCLUDE/cuttree.h
    ./concorde/INCLUDE/delaunay.h
    ./concorde/INCLUDE/edgegen.h
    ./concorde/INCLUDE/fmatch.h
    ./concorde/INCLUDE/heldkarp.h
    ./concorde/INCLUDE/kdtree.h
    ./concorde/INCLUDE/linkern.h
    ./concorde/INCLUDE/localcut.h
    ./concorde/INCLUDE/lp.h
    ./concorde/INCLUDE/machdefs.h
    ./concorde/INCLUDE/macrorus.h
    ./concorde/INCLUDE/mlinkern.h
    ./concorde/INCLUDE/necklace.h
    ./concorde/INCLUDE/pq.h
    ./concorde/INCLUDE/pqsets.h
    ./concorde/INCLUDE/tinytsp.h
    ./concorde/INCLUDE/tsp.h
    ./concorde/INCLUDE/util.h
    ./concorde/INCLUDE/verify.h
    ./concorde/INCLUDE/Makefile.common.in
    ./concorde/INCLUDE/config.h.in
    ./concorde/KDTREE/
    ./concorde/KDTREE/kdbuild.c
    ./concorde/KDTREE/kd_main.c
    ./concorde/KDTREE/kdnear.c
    ./concorde/KDTREE/kdspan.c
    ./concorde/KDTREE/kdtwoopt.c
    ./concorde/KDTREE/Makefile.in
    ./concorde/LINKERN/
    ./concorde/LINKERN/flip_two.c
    ./concorde/LINKERN/linkern.c
    ./concorde/LINKERN/linkern_fixed.c
    ./concorde/LINKERN/linkern_path.c
    ./concorde/LINKERN/lk_main.c
    ./concorde/LINKERN/testpath.c
    ./concorde/LINKERN/Makefile.in
    ./concorde/LOCALCUT/
    ./concorde/LOCALCUT/checker.c
    ./concorde/LOCALCUT/chunks.c
    ./concorde/LOCALCUT/first.c
    ./concorde/LOCALCUT/first_main.c
    ./concorde/LOCALCUT/intmat.c
    ./concorde/LOCALCUT/lift.c
    ./concorde/LOCALCUT/localcut.c
    ./concorde/LOCALCUT/loc_main.c
    ./concorde/LOCALCUT/peeler2.c
    ./concorde/LOCALCUT/peeler.c
    ./concorde/LOCALCUT/separate.c
    ./concorde/LOCALCUT/tsporacl.c
    ./concorde/LOCALCUT/Makefile.in
    ./concorde/LP/
    ./concorde/LP/lpcplex4.c
    ./concorde/LP/lpcplex5.c
    ./concorde/LP/lpcplex6.c
    ./concorde/LP/lpcplex8.c
    ./concorde/LP/lpnone.c
    ./concorde/LP/lpqsopt.c
    ./concorde/LP/Makefile.in
    ./concorde/PQ/
    ./concorde/PQ/consec1.c
    ./concorde/PQ/cuttree.c
    ./concorde/PQ/necklace.c
    ./concorde/PQ/pq.c
    ./concorde/PQ/pqtest.c
    ./concorde/PQ/Makefile.in
    ./concorde/TINY/
    ./concorde/TINY/bnbmsp.c
    ./concorde/TINY/tinytsp.c
    ./concorde/TINY/tt_main.c
    ./concorde/TINY/randtsp.awk
    ./concorde/TINY/Makefile.in
    ./concorde/TOOLS/
    ./concorde/TOOLS/edg2len.c
    ./concorde/TOOLS/edgunion.c
    ./concorde/TOOLS/fconvert.c
    ./concorde/TOOLS/junk.c
    ./concorde/TOOLS/killgrun.c
    ./concorde/TOOLS/lkhalone.c
    ./concorde/TOOLS/lkhboss.c
    ./concorde/TOOLS/lkhgrunt.c
    ./concorde/TOOLS/prob2tsp.c
    ./concorde/TOOLS/showres.c
    ./concorde/TOOLS/subby.c
    ./concorde/TOOLS/tdivide.c
    ./concorde/TOOLS/tour2edg.c
    ./concorde/TOOLS/tourchk.c
    ./concorde/TOOLS/tourlen.c
    ./concorde/TOOLS/ttour.c
    ./concorde/TOOLS/Makefile.in
    ./concorde/TSP/
    ./concorde/TSP/bcontrol.c
    ./concorde/TSP/blkcomb.c
    ./concorde/TSP/blossom.c
    ./concorde/TSP/bosstell.c
    ./concorde/TSP/branch.c
    ./concorde/TSP/cliqhash.c
    ./concorde/TSP/cliqwork.c
    ./concorde/TSP/combcliq.c
    ./concorde/TSP/concorde.c
    ./concorde/TSP/control.c
    ./concorde/TSP/cutcall.c
    ./concorde/TSP/cutpool.c
    ./concorde/TSP/cutserv.c
    ./concorde/TSP/ddecker.c
    ./concorde/TSP/domboss.c
    ./concorde/TSP/domgrunt.c
    ./concorde/TSP/domtest.c
    ./concorde/TSP/ex_price.c
    ./concorde/TSP/generate.c
    ./concorde/TSP/growcomb.c
    ./concorde/TSP/poolcat.c
    ./concorde/TSP/prclique.c
    ./concorde/TSP/prob_io.c
    ./concorde/TSP/probserv.c
    ./concorde/TSP/qsparse.c
    ./concorde/TSP/skeleton.c
    ./concorde/TSP/subboss.c
    ./concorde/TSP/subgate.c
    ./concorde/TSP/subgrunt.c
    ./concorde/TSP/teething.c
    ./concorde/TSP/test_tsp.c
    ./concorde/TSP/tighten.c
    ./concorde/TSP/tsp_call.c
    ./concorde/TSP/tsp_lp.c
    ./concorde/TSP/xtour.c
    ./concorde/TSP/Makefile.in
    ./concorde/UTIL/
    ./concorde/UTIL/allocrus.c
    ./concorde/UTIL/bgetopt.c
    ./concorde/UTIL/dheaps_i.c
    ./concorde/UTIL/edgelen.c
    ./concorde/UTIL/edgemap.c
    ./concorde/UTIL/edgeutil.c
    ./concorde/UTIL/eunion.c
    ./concorde/UTIL/fastread.c
    ./concorde/UTIL/genhash.c
    ./concorde/UTIL/getdata.c
    ./concorde/UTIL/priority.c
    ./concorde/UTIL/safe_io.c
    ./concorde/UTIL/signal.c
    ./concorde/UTIL/sortrus.c
    ./concorde/UTIL/subdiv.c
    ./concorde/UTIL/urandom.c
    ./concorde/UTIL/util.c
    ./concorde/UTIL/zeit.c
    ./concorde/UTIL/Makefile.in
    ./concorde/VERIFY/
    ./concorde/VERIFY/verify.c
    ./concorde/VERIFY/ver_main.c
    ./concorde/VERIFY/verlist.tst
    ./concorde/VERIFY/Makefile.in
    ./concorde/README
    loading cache ./config.cache
    checking host system type... Invalid configuration `x86_64-unknown-linux-gnu': machine `x86_64-unknown' not recognized
    
    checking for prespecified compiler options... no
    checking for gcc... (cached) gcc
    checking whether the C compiler (gcc -fPIC -O2 -g ) works... yes
    checking whether the C compiler (gcc -fPIC -O2 -g ) is a cross-compiler... no
    checking whether we are using GNU C... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking whether make sets ${MAKE}... (cached) no
    checking for ranlib... (cached) ranlib
    checking for sh... (cached) /bin/sh
    checking for file suffixes... o, a,
    checking for sqrt in -lm... (cached) yes
    checking for -lnsl... (cached) no
    checking for -lsocket... (cached) no
    checking for bfd_open_file in -lbfd... (cached) no
    checking for xstrerror in -liberty... (cached) no
    checking how to run the C preprocessor... (cached) gcc -E
    checking for ANSI C header files... (cached) yes
    checking whether time.h and sys/time.h may both be included... (cached) yes
    checking for stdlib.h... (cached) yes
    checking for math.h... (cached) yes
    checking for string.h... (cached) yes
    checking for strings.h... (cached) yes
    checking for errno.h... (cached) yes
    checking for assert.h... (cached) yes
    checking for sys/time.h... (cached) yes
    checking for time.h... (cached) yes
    checking for stddef.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for malloc.h... (cached) yes
    checking for sys/types.h... (cached) yes
    checking for sys/stat.h... (cached) yes
    checking for fcntl.h... (cached) yes
    checking for signal.h... (cached) yes
    checking for sys/socket.h... (cached) yes
    checking for netinet/in.h... (cached) yes
    checking for netdb.h... (cached) yes
    checking for sys/resource.h... (cached) yes
    checking for sys/param.h... (cached) yes
    checking for sys/times.h... (cached) yes
    checking for working const... (cached) yes
    checking for void... (cached) yes
    checking for size_t... (cached) yes
    checking for pid_t... (cached) yes
    checking return type of signal handlers... (cached) void
    checking for u_char... (cached) yes
    checking for missing printf prototype... (cached) no
    checking for missing gethostname prototype... (cached) no
    checking for missing getrusage prototype... (cached) no
    checking usable sigaction()... (cached) yes
    checking for __attribute__... (cached) yes
    checking for gethostname... (cached) yes
    checking for socket... (cached) yes
    checking for strdup... (cached) yes
    checking for getrusage... (cached) yes
    checking for times... (cached) yes
    checking for clock... (cached) yes
    checking for sleep... (cached) yes
    checking for sigaction... (cached) yes
    checking for signal... (cached) yes
    creating ./config.status
    creating Makefile
    creating BIGGUY/Makefile
    creating COMBS/Makefile
    creating CUT/Makefile
    creating EDGEGEN/Makefile
    creating FMATCH/Makefile
    creating HELDKARP/Makefile
    creating INCLUDE/Makefile.common
    creating KDTREE/Makefile
    creating LINKERN/Makefile
    creating LOCALCUT/Makefile
    creating LP/Makefile
    creating PQ/Makefile
    creating TINY/Makefile
    creating TOOLS/Makefile
    creating TSP/Makefile
    creating UTIL/Makefile
    creating VERIFY/Makefile
    creating INCLUDE/config.h
    INCLUDE/config.h is unchanged
    /bin/sh: 1: make: not found
    /tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/williamwhites/pyconcorde/setup.py", line 147, in <module>
        setup(
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-pv7le9wy/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/williamwhites/pyconcorde/setup.py", line 121, in run
        build_concorde()
      File "/home/williamwhites/pyconcorde/setup.py", line 109, in build_concorde
        _run("make", "build/concorde")
      File "/home/williamwhites/pyconcorde/setup.py", line 87, in _run
        subprocess.check_call(cmd, shell=True, cwd=cwd)
      File "/home/williamwhites/anaconda3/envs/TSP/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make' returned non-zero exit status 127.
    building concorde
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/williamwhites/anaconda3/envs/TSP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/williamwhites/pyconcorde/setup.py'"'"'; __file__='"'"'/home/williamwhites/pyconcorde/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by jvkersch** [comment]
@Williamlittlewhite You don't have the `make` command installed. Run `sudo apt-get install build-essential` to get this and other tools. You will need a C compiler as well.

**Comment by Williamlittlewhite** [comment]
Thank you very much. I solved this problem successfully!
