### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by yzhang-gh** [jvkersch/pyconcorde#43]
There is a compatibility issue (as shown in the title) if `numpy>=1.20` is used.

The cause seems to be a change in the C API in `numpy`. I am not sure whether it can be solved by changing the `pyproject.toml`, but would like to post a workaround here in case it can be helpful for other users:

use `pip install -e . --no-build-isolation --no-binary :all:` instead of `pip install -e .` to install this package.

Reference: https://stackoverflow.com/a/66743692/8682688

**Comment by jvkersch** [comment]
@yzhang-gh Thanks for flagging this; a simple workaround is to exclude NumPy versions lower than 1.20. I've implemented this in #55.
