### ISSUE TITLE
One-line Installation instructions in README

### ISSUE THREAD

**Issue by johnnycrab** [jvkersch/pyconcorde#62]
First, thank you for this great project!

In the README for the one-line installation instruction, `pip install -e git+https://github.com/jvkersch/pyconcorde`, I think you should add `#egg=pyconcorde`, i.e. in full (the other one is old notation):

`pip install -e git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde`. 

Otherwise, pip will throw you the error
`ERROR: Could not detect requirement name for 'git+https://github.com/jvkersch/pyconcorde', please specify one with #egg=your_package_name`.

Thanks a lot!

**Comment by theblinkingusb** [comment]
Agreed - added #66 if @jvkersch would like to merge and/or has feedback

**Comment by jvkersch** [comment]
Thanks guys!
