### ISSUE TITLE
is it possible to run this on custom data? 

### ISSUE THREAD

**Issue by davidireland3** [jvkersch/pyconcorde#64]
If I want to e.g. run the TSPSolver on some randomly generated co-ordinates is this possible? an example use case would literally be to generate some points uniformly at random which correspond to the city co-ordinates and find the optimal route between them.

**Comment by berkkarasu** [comment]
Yes, .tsplib format allows you to have your own distance matrix. If you assume that you have your distance matrix in dist_matrix
```
def create_tsp_file(file_path, dist_matrix):
        with open(file_path + '.tsp', 'w') as f:
            n = len(dist_matrix)
            f.write("NAME: temp\n")
            f.write(f"TYPE: TSP\n")
            f.write(f"DIMENSION: {n}\n")
            f.write("EDGE_WEIGHT_TYPE: EXPLICIT\n")
            f.write("EDGE_WEIGHT_FORMAT: FULL_MATRIX\n")
            f.write("EDGE_WEIGHT_SECTION\n")

            for row in dist_matrix:
                f.write(" ".join(str(int(dist)) for dist in row) + "\n")

            f.write("EOF\n")
```
If your distances are small, pyconcorde may possibly not solve your problem. Multiplying the distances with a huge number may help you to get a solution.

**Comment by davidireland3** [comment]
Thanks, I managed to figure it out in the end. Also, thanks for pointing out small distances may not be properly solvable -- I was using examples sampled from the unit square and was able to find better solutions used learned heuristics, so that makes sense now. I can just multiply the coordinates by a constant like you say when I give it to pyconcorde.
